// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmkB8QrhNLc5k9XrVV7LFbHB6i2F5dP6Q',
    appId: '1:735078431346:web:41902c51448da078a160eb',
    messagingSenderId: '735078431346',
    projectId: 'project-b5aae',
    authDomain: 'project-b5aae.firebaseapp.com',
    storageBucket: 'project-b5aae.appspot.com',
    measurementId: 'G-JBNGJW8281',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8SuGg7Nepf2j4CVx91U3LudiK83NtRKY',
    appId: '1:735078431346:android:00a6fe6f3ad06668a160eb',
    messagingSenderId: '735078431346',
    projectId: 'project-b5aae',
    storageBucket: 'project-b5aae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg7ukeAKfjP2d3zA0-n_cu1CBz8uSoAWE',
    appId: '1:735078431346:ios:23aa29b328176dafa160eb',
    messagingSenderId: '735078431346',
    projectId: 'project-b5aae',
    storageBucket: 'project-b5aae.appspot.com',
    iosBundleId: 'com.example.success',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmkB8QrhNLc5k9XrVV7LFbHB6i2F5dP6Q',
    appId: '1:735078431346:web:8c427c78dbf5b17ba160eb',
    messagingSenderId: '735078431346',
    projectId: 'project-b5aae',
    authDomain: 'project-b5aae.firebaseapp.com',
    storageBucket: 'project-b5aae.appspot.com',
    measurementId: 'G-6C5MC2FVKY',
  );
}
